[package]
name = "mkdocs-djot"
version = "0.1.0"
edition = "2024"

[lib]
name = "jotdown_py"
crate-type = ["cdylib"]

[dependencies]
jotdown = "0.9.0"
pyo3 = { version = "0.27.1", features = ["extension-module"] }
